Add Python Attribute Accessors and Cross-Library Compatibility for PkEncryption
matrix-nio/vodozemac-python pull request #15
Opened 2024-12-10 14:35 UTC by TrevisGordan

This PR adds missing Python attribute accessors and improves compatibility with python-olm by enabling cross-library encryption and decryption tests.

**Details**:

- Adds `#[pyo3(get)]` annotations to the `Message` struct fields (`ciphertext`, `mac`, `ephemeral_key`), making these attributes accessible from Python.
- Implements a `Message` constructor in Rust (via `#[new]`), allowing Python code to create `Message` instances directly.
- Introduces tests to verify that attribute access works as intended.
- Adds integration tests to ensure `PkEncryption` is compatible with python-olm. Specifically:
  - Encrypt with Olm and decrypt with Vodozemac.
  - Encrypt with Vodozemac and decrypt with Olm.
  
**Next Steps**:

To achieve seamless compatibility, the user will need to Base64-encode Vodozemac message attributes (ciphertext, mac, ephemeral_key) before passing them to Olm. For example:

```python
vodo_encryption = PkEncryption.from_key(public_key)
vodo_message = vodo_encryption.encrypt(PLAINTEXT).encode())

vodo_mac = base64.b64encode(vodo_message.mac).decode('ascii')
vodo_ciphertext = base64.b64encode(vodo_message.ciphertext).decode('ascii')
vodo_ephemeral_key = base64.b64encode(vodo_message.ephemeral_key).decode('ascii')
```

A future enhancement could add a Rust helper function to handle this encoding automatically, such as:

```python
(ciphertext, mac, ephemeral_key) = encryption.encrypt(json.dumps(media_body).encode()).to_base64()
```
Also `unpad_base64_encode` and `pad_base64_decode` functions. 
This would streamline the process and reduce the amount of Python-side encoding logic required.

2025-01-08 14:44 UTC, poljar requested changes
Thanks for writing this and sorry for the delay here. I left some small nits.

2025-01-08 14:44 UTC, poljar commented on requirements-dev.txt
> +python-olm==3.2.16
Missing newline.

2025-01-08 14:44 UTC, poljar commented on src/pk_encryption.rs
> +    #[new]
Please add some documentation for this method.

2025-01-08 14:44 UTC, poljar commented on tests/pk_encryption_test.py
> +        def pad_base64_decode(b64_str: str) -> bytes:
I'm fine with adding another constructor to the `Message` type, i.e. `Message.from_base64(ciphertext, mac, key)`.

The same applies to the other direction: `ciphertext, mac, key = message.to_base64()`.

2025-01-08 15:42 UTC, TrevisGordan commented on tests/pk_encryption_test.py
> +        def pad_base64_decode(b64_str: str) -> bytes:
Yes..., I’ve put this off for now and separated it out in [issue #16](https://github.com/matrix-nio/vodozemac-python/issues/16). My Rust knowledge is currently quite limited, and Vec<u8> didn’t work out for me—especially given that the legacy olm.pk.PkEncryption uses a rather creative base64 encoding implementation.

But if you have a direction / idea, I'm happy to continue that part later on!

2025-01-08 15:53 UTC, poljar commented on tests/pk_encryption_test.py
> +        def pad_base64_decode(b64_str: str) -> bytes:
Ah right, I remember this now. Doesn't https://docs.rs/vodozemac/latest/vodozemac/fn.base64_decode.html just work? As far as I know libolm just uses unpadded base64.

2025-01-09 13:58 UTC, TrevisGordan commented on tests/pk_encryption_test.py
> +        def pad_base64_decode(b64_str: str) -> bytes:
Ah, that’s the missing piece! I wasn’t aware of that function—thank you. Yes, for some (undocumented) reason it does behave that way; I initially only discovered it through trial and error.

With the compatible base64_decode/base64_encode functions, everything works perfectly now. I was able to implement a from_base64class method and a to_base64 method directly. Please take a look. I also removed that hacky b64 padding helper from the tests. Please double-check if everything is solid.

https://github.com/matrix-nio/vodozemac-python/blob/81fa80980140605c3d323ad326eb2ac062e2bc9c/src/pk_encryption.rs#L51-L97

2025-01-10 11:53 UTC, poljar requested changes
Some two minor things left to do, then I think we can merge.

2025-01-13 13:08 UTC, TrevisGordan commented on src/pk_encryption.rs
> +    fn to_base64<'py>(
Hey, Yes, Seems like both versions will do it.
I was just reading about explicit conversion being more efficient. 

2025-01-13 13:09 UTC, TrevisGordan commented on src/pk_encryption.rs
> +            vodozemac::base64_decode(ciphertext).expect("Failed to decode ciphertext");
Ok, i see - yes.
Please double-check this, if this fits the purpose. 
I also added a test for that exception.

2025-01-13 13:13 UTC, poljar commented on src/pk_encryption.rs
> +    fn to_base64<'py>(
Oh, is it? I would expect it to perform the same. Do you have a reference for that?

2025-01-13 13:44 UTC, TrevisGordan commented on src/pk_encryption.rs
> +    fn to_base64<'py>(
At least that was my understanding mainly from:
https://pyo3.rs/v0.11.1/conversions#returning-rust-values-to-python
https://pyo3.rs/v0.23.4/types.html#pyo3s-smart-pointers
But definitely nothing I would argue about. 
And probably more in the area of unnecessary early optimization.

2025-01-13 13:52 UTC, poljar requested changes
Great, I think this is good to go functionality-wise.

Could you just fix the formatting you'll have to use `rustmfmt` nightly for this:

```bash
$ cargo +nightly fmt
```

2025-01-13 13:52 UTC, poljar commented on tests/pk_encryption_test.py
> +            )
```suggestion
            )

```

2025-03-11 11:07 UTC, TrevisGordan commented
Hey @poljar 

The CI/CD Error appears to be a known issue – libolm cannot be built on Windows easily (see https://github.com/matrix-org/olm/issues/25). Given its deprecation, I don’t expect Windows support to ever be added.

Skipping all Windows tests might be overkill. Instead, we could skip the libolm tests via pytest options to avoid import errors. One option is to create a separate requirements file (e.g. requirements-dev-win.txt); another option is to dynamically modify the requirements-dev.txt file in the noxfile by removing the libolm dependency (a bit hacky tho).

For example:

```python
import nox
import os

@nox.session(python=["3.9", "3.10", "3.11", "3.12"])
def test(session):
    if os.name == 'nt':  # Check if the OS is Windows
        session.log("Skipping libolm tests on Windows due to known issues.")
        # Option 1: Use a separate requirements file (requirements-dev-win.txt)
        # Option 2: Dynamically remove the "python-olm==3.2.16" dependency from requirements-dev.txt
        session.install("-r requirements-dev-win.txt")
        session.install("-e", ".", "--no-build-isolation")
        session.run("pytest --ignore=tests/pk_encryption_test.py")
        return

    session.install("-r requirements-dev.txt")
    session.install("-e", ".", "--no-build-isolation")
    session.run("pytest")
```

What do you think? Or you may even have a better idea?

2025-06-30 09:29 UTC, poljar approved these changes

2025-06-30 12:26 UTC, TrevisGordan commented
LGTM Thanks Guys!

2025-06-30 17:15 UTC, merged